name: mg_test
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mpi=1.0
  - mpich=3.3.2
  - ncurses=6.4
  - openssl=3.0.13
  - python=3.11.4
  - readline=8.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
    - blobfile==2.1.1
    - certifi==2022.12.7
    - charset-normalizer==2.1.1
    - cmake==3.25.0
    - filelock==3.9.0
    - idna==3.4
    - jinja2==3.1.2
    - joblib==1.3.2
    - lit==15.0.7
    - lpips==0.1.4
    - lxml==4.9.4
    - markupsafe==2.1.3
    - mpi4py==3.1.4
    - mpmath==1.3.0
    - networkx==3.2.1
    - numpy==1.26.3
    - pillow==10.2.0
    - pip==23.3.1
    - pycryptodomex==3.20.0
    - requests==2.28.1
    - scikit-learn==1.4.0
    - scipy==1.12.0
    - setuptools==68.2.2
    - sympy==1.12
    - threadpoolctl==3.2.0
    - torch==2.0.1+cu117
    - torchaudio==2.0.2+cu117
    - torchvision==0.15.2+cu117
    - tqdm==4.66.2
    - triton==2.0.0
    - typing-extensions==4.8.0
    - urllib3==1.26.13
    - wheel==0.41.2